CREATE TABLE [dbo].[AppUser]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Username] VARCHAR(50) NOT NULL,
	[FirstName] VARCHAR(100) NOT NULL,	  
	[LastName] VARCHAR(50) NOT NULL,	  
	[Password] VARCHAR(20) NOT NULL,	
	[Email] VARCHAR(100) NOT NULL,
	[CreationDate] DATETIME NOT NULL DEFAULT GETDATE(),
	[CreatedBy] INT NOT NULL DEFAULT 0,
	[UdateDate] DATETIME NULL,
	[UdatedBy] INT NULL
)