CREATE TABLE [dbo].[ToDos]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Todo] VARCHAR(200) NOT NULL,
	[CreationDate] DATETIME NOT NULL DEFAULT GETDATE(),
	[DueDate] DATETIME,
	[Finish] BIT NULL DEFAULT 0
)
