CREATE TABLE [dbo].[Todos]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(200) NOT NULL,
	[CreationDate] DATETIME NOT NULL DEFAULT GETDATE(),
	[DueDate] DATETIME,
	[Finished] BIT NULL DEFAULT 0
)
